version: '3.8'

services:
  app:
    image: dashboards-csv:latest
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.dashcsv.rule=Host(`dashcsv.arxsolutions.cloud`)"
        - "traefik.http.routers.dashcsv.entrypoints=websecure"
        - "traefik.http.routers.dashcsv.tls=true"
        - "traefik.http.routers.dashcsv.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.dashcsv.loadbalancer.server.port=3000"
        - "traefik.docker.network=rede_principal"
    environment:
      PORT: "3000"
      NODE_ENV: "production"
      GEMINI_API_KEY: "${GEMINI_API_KEY}"
    networks:
      - rede_principal

networks:
  rede_principal:
    external: true
